"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";

declare const __APP_VERSION__: string;

type Service={id:string;date:string;day:string;type:"Lehr"|"Gebet";song:string;songBy:string;text:string;textBy:string;vorrade:string;status:string;notes:string};
type ApiService={id:string;service_date:string;service_type:"LEHR"|"GEBET";song:string;song_by:string;text_title:string;text_by:string;vorrade:string|null;lehr_status:"IN_PROGRESS"|"FINISHED"|null;notes:string|null};
type EntryType=""|"Lehr"|"Gebet";
const nav=["Register","Texts","Vorraden","Songs","People"];
const blankDraft=()=>({date:"",type:"" as EntryType,song:"",songBy:"",text:"",textBy:"",vorrade:"",notes:""});
const apiUrl=()=>"/api/services";
const fromApi=(row:ApiService):Service=>{const d=new Date(`${row.service_date}T12:00:00`);return{id:row.id,date:d.toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}),day:d.toLocaleDateString("en-US",{weekday:"long"}),type:row.service_type==="LEHR"?"Lehr":"Gebet",song:row.song,songBy:row.song_by,text:row.text_title,textBy:row.text_by,vorrade:row.vorrade||"—",status:row.lehr_status==="IN_PROGRESS"?"In progress":row.lehr_status==="FINISHED"?"Finished":"—",notes:row.notes||""}};

export default function Home(){
 const [active,setActive]=useState("Register"),[items,setItems]=useState<Service[]>([]),[query,setQuery]=useState(""),[filter,setFilter]=useState("All services"),[open,setOpen]=useState(false),[mobile,setMobile]=useState(false),[kind,setKind]=useState<EntryType>(""),[selected,setSelected]=useState<Service|null>(null),[rowVersion,setRowVersion]=useState(0),[saveError,setSaveError]=useState("");
 const [draft,setDraft]=useState(blankDraft);
 useEffect(()=>{const media=window.matchMedia("(max-width: 520px)");const update=()=>setMobile(media.matches);update();media.addEventListener("change",update);return()=>media.removeEventListener("change",update)},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>{const saved=sessionStorage.getItem("sermon-register-service-draft");if(saved){try{setDraft({...blankDraft(),...JSON.parse(saved)});setRowVersion(v=>v+1)}catch{sessionStorage.removeItem("sermon-register-service-draft")}}},0);return()=>window.clearTimeout(timer)},[]);
 useEffect(()=>{fetch(apiUrl()).then(r=>{if(!r.ok)throw new Error("Database unavailable");return r.json()}).then(rows=>setItems((rows as ApiService[]).map(fromApi))).catch(()=>setSaveError("The SQLite database could not be reached. Check the container logs."))},[]);
 const visible=useMemo(()=>items.filter(x=>(filter==="All services"||x.type===filter)&&Object.values(x).join(" ").toLowerCase().includes(query.toLowerCase())),[items,query,filter]);
 async function createService(payload:Record<string,string>){setSaveError("");const response=await fetch(apiUrl(),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json() as ApiService&{error?:string};if(!response.ok)throw new Error(result.error||"Could not save service");setItems(v=>[fromApi(result),...v])}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!kind)return;const f=new FormData(e.currentTarget);try{await createService({date:String(f.get("date")),type:kind.toUpperCase(),song:String(f.get("song")),songBy:String(f.get("songBy")),text:String(f.get("text")),textBy:String(f.get("textBy")),vorrade:String(f.get("vorrade")||""),notes:String(f.get("notes")||"")});setOpen(false)}catch(err){setSaveError(err instanceof Error?err.message:"Could not save service")}}
 function persistInlineDraft(){const form=document.getElementById("inline-service-form") as HTMLFormElement|null;if(!form)return;const f=new FormData(form);sessionStorage.setItem("sermon-register-service-draft",JSON.stringify({date:String(f.get("inlineDate")||""),type:String(f.get("inlineType")||"") as EntryType,song:String(f.get("inlineSong")||""),songBy:String(f.get("inlineSongBy")||""),text:String(f.get("inlineText")||""),textBy:String(f.get("inlineTextBy")||""),vorrade:String(f.get("inlineVorrade")||""),notes:String(f.get("inlineNotes")||"")}))}
 async function saveInline(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),date=String(f.get("inlineDate")),type=String(f.get("inlineType")) as EntryType,song=String(f.get("inlineSong")||"").trim(),songBy=String(f.get("inlineSongBy")||"").trim(),text=String(f.get("inlineText")||"").trim(),textBy=String(f.get("inlineTextBy")||"").trim(),vorrade=String(f.get("inlineVorrade")||"").trim(),notes=String(f.get("inlineNotes")||"");if(!date||!type||!song||!songBy||!text||!textBy){setSaveError("Complete Date, Type, Song, Song By, Text, and Text By.");return}try{await createService({date,type:type.toUpperCase(),song,songBy,text,textBy,vorrade,notes});sessionStorage.removeItem("sermon-register-service-draft");setDraft(blankDraft());setRowVersion(v=>v+1)}catch(err){setSaveError(err instanceof Error?err.message:"Could not save service")}}
 function clearInline(){sessionStorage.removeItem("sermon-register-service-draft");setDraft(blankDraft());setRowVersion(v=>v+1)}
 function startNew(){setActive("Register");clearInline();setKind("");if(mobile)setOpen(true)}
 return <main className="shell">
  <aside className="side"><div className="brand"><b>S</b><span>Sermon Register</span></div><nav>{nav.map(n=><button key={n} className={active===n?"on":""} onClick={()=>setActive(n)}>{n}</button>)}</nav><small>● &nbsp; Private register</small></aside>
  <section className="work"><form id="inline-service-form" onSubmit={saveInline}/><header className="top"><div className="mobilebrand"><b>S</b><span>Sermon Register</span></div><span className="crumb">Sermon Register &nbsp;/&nbsp; {active}</span><div className="top-actions"><span className="app-version" aria-label={`Version ${__APP_VERSION__}`}>v{__APP_VERSION__}</span><button className="primary" onClick={startNew}>＋ New service</button></div></header>
   <div className="content"><div className="heading"><div><span>2026 archive</span><h1>{active==="Register"?"Service register":active}</h1><p>{active==="Register"?"Weekly Lehr and Gebet history":`Reusable ${active.toLowerCase()} records`}</p></div><span>{items.length} services</span></div>
   {active==="Register"?<><div className="tools"><div className="search">⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search texts, songs, people, or notes" aria-label="Search"/></div><select value={filter} onChange={e=>setFilter(e.target.value)} aria-label="Service type"><option>All services</option><option>Lehr</option><option>Gebet</option></select><select aria-label="Year"><option>2026</option><option>2025</option></select></div>{saveError&&<div className="save-error" role="alert">{saveError}</div>}
   <div className="tablebox"><table><thead><tr><th>Date</th><th>Type</th><th>Song</th><th>Song by</th><th>Text</th><th>Text by</th><th>Vorrade</th><th>Status</th><th>Notes</th></tr></thead><tbody><tr className="inline-row" key={rowVersion} onInput={persistInlineDraft}><td><input form="inline-service-form" name="inlineDate" type="date" defaultValue={draft.date}/></td><td><select form="inline-service-form" name="inlineType" value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value as EntryType})}><option value="">Choose type</option><option>Lehr</option><option>Gebet</option></select></td><td><input form="inline-service-form" name="inlineSong" list="songs-list" defaultValue={draft.song} placeholder="Choose or type new"/></td><td><input form="inline-service-form" name="inlineSongBy" list="people-list" defaultValue={draft.songBy} placeholder="Choose or type new"/></td><td><input form="inline-service-form" name="inlineText" list="texts-list" defaultValue={draft.text} placeholder="Choose or type new"/></td><td><input form="inline-service-form" name="inlineTextBy" list="people-list" defaultValue={draft.textBy} placeholder="Choose or type new"/></td><td>{draft.type==="Lehr"?<input form="inline-service-form" name="inlineVorrade" list="vorraden-list" defaultValue={draft.vorrade} placeholder="Choose or type new"/>:"—"}</td><td><span className="inline-actions"><button form="inline-service-form" type="submit" className="row-save">Save</button><button type="button" onClick={clearInline}>Clear</button></span></td><td><input form="inline-service-form" name="inlineNotes" defaultValue={draft.notes} placeholder="Add notes"/></td></tr>{visible.map(x=><tr key={x.id} role="button" tabIndex={0} onClick={()=>setSelected(x)} onKeyDown={e=>(e.key==="Enter"||e.key===" ")&&setSelected(x)}><td><strong>{x.date}</strong><small>{x.day}</small></td><td><i className={x.type.toLowerCase()}/>{x.type}</td><td>{x.song}</td><td>{x.songBy}</td><td><strong>{x.text}</strong></td><td>{x.textBy}</td><td>{x.vorrade}</td><td><em>{x.status}</em></td><td className="muted">{x.notes}</td></tr>)}</tbody></table>{!visible.length&&<div className="empty">No services match your search.</div>}</div>
   <div className="cards">{visible.map(x=><button key={x.id} onClick={()=>setSelected(x)}><span><strong>{x.day}, {x.date}</strong><mark><i className={x.type.toLowerCase()}/>{x.type}</mark></span><b>{x.text}</b><small>{x.song} · {x.textBy}</small><em>{x.status}</em></button>)}</div></>:<div className="placeholder"><b>{active[0]}</b><h2>{active}</h2><p>This reusable-record view is ready for the next development stage.</p></div>}</div>
   <nav className="bottomnav">{nav.slice(0,4).map(n=><button key={n} className={active===n?"on":""} onClick={()=>setActive(n)}><b>{n==="Register"?"▤":n==="Songs"?"♪":"◇"}</b>{n}</button>)}</nav>
  </section>
  {open&&<div className="overlay" role="button" tabIndex={-1} onKeyDown={e=>e.key==="Escape"&&setOpen(false)} onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><section className="dialog" role="dialog" aria-modal="true"><header><div><span>Register entry</span><h2>New service</h2></div><button onClick={()=>setOpen(false)} aria-label="Close">×</button></header><form onSubmit={save}><div className="grid"><label>Date<input name="date" type="date" required/></label><label>Service type<select value={kind} onChange={e=>setKind(e.target.value as EntryType)} required><option value="">Choose type</option><option>Lehr</option><option>Gebet</option></select></label><label>Song<input name="song" list="songs-list" placeholder="Choose or type a new song" required/></label><label>Song by<input name="songBy" list="people-list" placeholder="Choose or type a new person" required/></label><label className="wide">Text<input name="text" list="texts-list" placeholder="Choose or type a new text" required/></label><label>Text by<input name="textBy" list="people-list" placeholder="Choose or type a new person" required/></label>{kind==="Lehr"&&<label>Vorrade<input name="vorrade" list="vorraden-list" placeholder="Choose or type a new Vorrade"/></label>}<label className="wide">Notes<textarea name="notes" placeholder="Notes for this service"/></label></div><footer><button type="button" onClick={()=>setOpen(false)}>Cancel</button><button className="primary">Save service</button></footer></form></section></div>}
  {selected&&<div className="overlay right" role="button" tabIndex={-1} onKeyDown={e=>e.key==="Escape"&&setSelected(null)} onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><aside className="detail"><button className="x" onClick={()=>setSelected(null)} aria-label="Close details">×</button><mark><i className={selected.type.toLowerCase()}/>{selected.type}</mark><h2>{selected.text}</h2><p>{selected.day}, {selected.date}</p><dl>{[["Song",selected.song],["Song by",selected.songBy],["Text by",selected.textBy],["Vorrade",selected.vorrade],["Status",selected.status],["Notes",selected.notes]].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b||"—"}</dd></div>)}</dl><section><div><b>PDF attachments</b><small>Documents for this service stay private.</small></div><button>＋ Add PDF</button></section></aside></div>}
  <datalist id="songs-list"><option value="#127 Immanuel"/><option value="#43 Abendfriede"/><option value="#81 Gnade"/><option value="#112 Vertrauen"/></datalist><datalist id="people-list"><option value="John Hofer"/><option value="Peter Waldner"/><option value="Jacob Wollman"/></datalist><datalist id="texts-list"><option value="Matthew 5:43–48"/><option value="John 15:1–11"/><option value="Psalm 27"/><option value="Romans 8:18–30"/></datalist><datalist id="vorraden-list"><option value="Vorrade 18"/><option value="Vorrade 12"/><option value="Vorrade 7"/></datalist>
 </main>
}
